/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-17 14:01:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.main.registration.servlets.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1678981210735L));
    _jspx_dependants.put("jar:file:/C:/Users/Rudra/OneDrive/Desktop/programs/rathansir/RathanSir/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FirstProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("jar:file:/C:/Users/Rudra/OneDrive/Desktop/programs/rathansir/RathanSir/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FirstProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.main.registration.servlets");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Edit User</title>\r\n");
      out.write("<style>\r\n");
      out.write("form {\r\n");
      out.write("	margin-top: 7%;\r\n");
      out.write("	background-color: aquamarine;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	border: 3px blue solid;\r\n");
      out.write("}\r\n");
      out.write("center{\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-family: \"Arial Black\";\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url(\"sp4.jpg\");\r\n");
      out.write("	background-color: aquamarine;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 40px;\r\n");
      out.write("	font-family: bold;\r\n");
      out.write("	color: #ff1a75;\r\n");
      out.write("    border: 1px solid rgb(69, 7, 40);\r\n");
      out.write("    background-color:rgb(69, 7, 40);\r\n");
      out.write("    height: 60px;\r\n");
      out.write("}\r\n");
      out.write("input {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	font-family: \"Arial Black\";\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-family: \"Arial Black\";\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		String username = request.getParameter("username");

	
      out.write("\r\n");
      out.write("	<center>\r\n");
      out.write("	<h1>Edit User: ");
      out.print( username );
      out.write("</h1>\r\n");
      out.write("	<form action=\"./UpdateServlet\" method=\"GET\">\r\n");
      out.write("		<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><label>Current Username:</label></td>\r\n");
      out.write("					<td><input type=\"text\" placeholder=\"");
      out.print( username );
      out.write("\" name=\"uname\" value=\"");
      out.print( username );
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><label>Email:</label></td>\r\n");
      out.write("					<td><input type=\"text\" placeholder=\"Enter Email\" name=\"email\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><label>New Username:</label></td>\r\n");
      out.write("					<td><input type=\"text\" placeholder=\"Enter Username\"\r\n");
      out.write("						name=\"username\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><label>Password:</label></td>\r\n");
      out.write("					<td><input type=\"password\" placeholder=\"Enter Password\"\r\n");
      out.write("						name=\"password\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><label>Number:</label></td>\r\n");
      out.write("					<td><input type=\"text\" placeholder=\"Enter Mobile Number\"\r\n");
      out.write("						name=\"number\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<input type=\"submit\" value=\"Save\">\r\n");
      out.write("	</form>\r\n");
      out.write("	</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
